version: '3.7'

services:
    balancer:
        image: nginx
        container_name: balancer
        ports: 
            - 80:80/tcp
        volumes: 
            - /home/deastro/dev/DevOps/VagrantDockerPacker/1.7plus/nginx/etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        links: 
            - web
    web:
        build: .
        container_name: web
        volumes:
            - /home/deastro/dev/DevOps/VagrantDockerPacker/1.7plus/web/etc/sites-enabled:/etc/apache2/sites-enabled
            - /home/deastro/dev/DevOps/VagrantDockerPacker/1.7plus/web/www:/var/www/site
        links: 
            - mysql57
    mysql57:
        image: percona:5.7
        container_name: mysql
        # ports:
        #     - 3307:3307
        environment:
            MYSQL_ROOT_PASSWORD: 710985465771My
        # volumes:
        #     - ./mysql/configs/my.cnf:/etc/mysql/conf.d/custom.cnf
        #     - ./mysql/mysql:/var/lib/mysql
    tomcat:
        build: tomcat
        container_name: tomcat
        ports: 
            - 8080:8080/tcp